version: '3.8'

services:

  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: product-catalog
    ports:
      - "3000:3000"
    depends_on:
      - mongo